apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-service-app
  labels:
    app: apigateway-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway-service-app
  template:
    metadata:
      labels:
        app: apigateway-service-app
    spec:
      containers:
        - name: apigateway-service-app
          image: ifcglobalpoc.azurecr.io/apigateway
          imagePullPolicy: Always
          ports:
            - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-service-svc
spec:
  ports:
    - targetPort: 9000
      port: 80
  selector:
    app: apigateway-service-app