server:
  port: 9000
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MANAGEMENT-SERVICE
          uri: lb://MANAGEMENT-SERVICE
          predicates:
            - Path=/management/**
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka